GRANT CONNECT ON DATABASE "HealthCareDB" TO sqlprojects;
GRANT USAGE ON SCHEMA public TO sqlprojects;
GRANT INSERT, SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO sqlprojects;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO sqlprojects;

